# Generated by Django 3.2.9 on 2022-02-06 17:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='explanation',
            field=ckeditor.fields.RichTextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Yükle'),
        ),
    ]
